### ISSUE TITLE
AccountWithPin and Account

### ISSUE THREAD

**Issue by arctarus44** [arctarus44/fake-bank#14]
I think the class AccountWithPin must extend the class Account.

It will be easier to maintain, and cleaner.

**Comment by calve** [comment]
That's what I tried in the first time but I had issue with inheritance, most notably the fact that Hibernate tries to match the class name to the table. So when ``AccountWithPin`` inherits from ``Account``, Hibernate complains (with reason) that there is no SQL table with this name.

However, feel free to try to implements it (and **test** it), you may have better luck

**Comment by arctarus44** [comment]
Done see #15
